version: '3.8'

services:
  db:
    image: library/postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./dvdrental:/docker-entrypoint-initdb.d

