name: Run SchemaSpy

on:
  workflow_dispatch:

jobs:
  schemaspy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.3.0

      - name: run database
        run: docker-compose up -d

      - name: run schemaspy
#        run: docker run -u root -v "$PWD/output:/output" --net="host" schemaspy/schemaspy:latest -t pgsql -host $(ip -f inet -o addr show docker0 | awk '{print $4}' | cut -d '/' -f 1):5432 -db postgres -u postgres -p password
        run: docker run -u root -v "$PWD/output:/output" --net="host" schemaspy/schemaspy:snapshot -t pgsql -host $(ip -f inet -o addr show docker0 | awk '{print $4}' | cut -d '/' -f 1):5432 -db dvdrental -u postgres -p password


      - name: create PR
        run: |
          BRANCH=docs/db/$(date +%Y%m%d%H%M%S)
          git config user.name github-actions
          git config user.email github-actions@github.com
          git switch -c $BRANCH
          git add output
          git commit -m "Update database docs"
          git push --set-upstream origin $BRANCH
          gh pr create --title "Update Database docs" --body ":smiley:"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: merge PR
        run: |
          gh pr review --approve
          gh pr merge --squash
        env:
          GH_TOKEN: ${{ secrets.TOKEN }}

      - name: stop database
        run: docker-compose down
