name: Run SchemaSpy

on:
  workflow_dispatch:

jobs:
  schemaspy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.3.0

      - name: run database
        run: docker-compose up -d

      - name: run schemaspy
        run: docker run -u root -v "$PWD/output:/output" schemaspy/schemaspy:latest -t pgsql -host localhost:5432 -db dvdrental -u postgres -p password

      - run: ls output

      - name: stop database
        run: docker-compose down
